apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengovpension.fullname" . }}-secrets
  labels:
    {{- include "opengovpension.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.app.secrets.databaseUrl }}
  database-url: {{ .Values.app.secrets.databaseUrl | b64enc }}
  {{- else }}
  database-url: {{ include "opengovpension.database.url" . | b64enc }}
  {{- end }}
  {{- if .Values.app.secrets.redisUrl }}
  redis-url: {{ .Values.app.secrets.redisUrl | b64enc }}
  {{- else }}
  redis-url: {{ include "opengovpension.redis.url" . | b64enc }}
  {{- end }}
  {{- if .Values.app.secrets.jwtSecret }}
  jwt-secret: {{ .Values.app.secrets.jwtSecret | b64enc }}
  {{- else }}
  jwt-secret: {{ "change_me_in_production" | b64enc }}
  {{- end }}
  {{- if .Values.app.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.app.secrets.openaiApiKey | b64enc }}
  {{- else }}
  openai-api-key: {{ "change_me_in_production" | b64enc }}
  {{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengovpension.postgresql.fullname" . }}
  labels:
    {{- include "opengovpension.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengovpension.redis.fullname" . }}
  labels:
    {{- include "opengovpension.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.auth.existingSecret }}
  redis-password: {{ .Values.redis.auth.existingSecret | b64enc }}
  {{- else if .Values.redis.auth.password }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- end }}
{{- end }}
---
{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengovpension.grafana.fullname" . }}
  labels:
    {{- include "opengovpension.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ "admin" | b64enc }}
  admin-password: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
{{- end }}
---
{{- if .Values.app.ingress.enabled }}
{{- if .Values.app.ingress.tls }}
{{- range .Values.app.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "opengovpension.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ "change_me_with_actual_cert" | b64enc }}
  tls.key: {{ "change_me_with_actual_key" | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}