apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opengovpension-api-hpa
  labels:
    app: opengovpension
    component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opengovpension-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  - type: Pods
    pods:
      metric:
        name: active_connections
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
      - type: Pods
        value: 1
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
      - type: Pods
        value: 2
      selectPolicy: Max
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opengovpension-metrics-config
  labels:
    app: opengovpension
    component: api
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
    scrape_configs:
    - job_name: 'opengovpension-api'
      static_configs:
      - targets: ['opengovpension-api:8001']
      scrape_interval: 5s
      metrics_path: /metrics
    - job_name: 'redis-exporter'
      static_configs:
      - targets: ['opengovpension-api:9121']
      scrape_interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: opengovpension-alerts
  labels:
    app: opengovpension
    component: api
spec:
  groups:
  - name: opengovpension
    rules:
    - alert: OpenGovPensionAPIDown
      expr: up{job="opengovpension-api"} == 0
      for: 5m
      labels:
        severity: critical
        service: opengovpension-api
      annotations:
        summary: "OpenGovPension API is down"
        description: "OpenGovPension API has been down for more than 5 minutes."

    - alert: OpenGovPensionAPIHighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
        service: opengovpension-api
      annotations:
        summary: "High error rate on OpenGovPension API"
        description: "Error rate is above 5% for more than 5 minutes."

    - alert: OpenGovPensionAPILatencyHigh
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
        service: opengovpension-api
      annotations:
        summary: "High latency on OpenGovPension API"
        description: "95th percentile latency is above 1 second for more than 5 minutes."

    - alert: OpenGovPensionAPICPUUsageHigh
      expr: rate(container_cpu_usage_seconds_total{pod=~"opengovpension-api-.*"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
        service: opengovpension-api
      annotations:
        summary: "High CPU usage on OpenGovPension API"
        description: "CPU usage is above 80% for more than 10 minutes."

    - alert: OpenGovPensionAPIMemoryUsageHigh
      expr: container_memory_usage_bytes{pod=~"opengovpension-api-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
        service: opengovpension-api
      annotations:
        summary: "High memory usage on OpenGovPension API"
        description: "Memory usage is above 90% for more than 5 minutes."

    - alert: OpenGovPensionAPIRateLimitExceeded
      expr: rate(http_requests_total{status="429"}[5m]) > 10
      for: 5m
      labels:
        severity: info
        service: opengovpension-api
      annotations:
        summary: "Rate limiting is active on OpenGovPension API"
        description: "More than 10 requests per minute are being rate limited."

    - alert: OpenGovPensionAPIDatabaseConnectionErrors
      expr: rate(database_connection_errors_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        service: opengovpension-api
      annotations:
        summary: "Database connection errors on OpenGovPension API"
        description: "Database connection errors detected."

    - alert: OpenGovPensionAPICircuitBreakerOpen
      expr: circuit_breaker_state{state="open"} > 0
      for: 1m
      labels:
        severity: warning
        service: opengovpension-api
      annotations:
        summary: "Circuit breaker is open on OpenGovPension API"
        description: "One or more circuit breakers are in open state."